spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:cache.yml,classpath:config.yml
  cloud:
    sentinel:
      transport:
        dashboard: ${kd.sentinel.url}
      datasource:
        flow:
          nacos:
            server-addr: ${kd.nacos.server.url}
            data-id: gateway-flow-rules
            group-id: SENTINEL_GROUP
            rule-type: GW_FLOW
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
      routes:
        - id: kd-auth
          uri: lb://kd-auth
          predicates:
            - Path=/auth/**,/token/**
        - id: kd-business
          uri: lb://kd-business
          predicates:
            - Path=/user/**
        - id: kd-admin
          uri: lb://kd-admin
          predicates:
            - Path=/admin/**
server:
  port: 8081
logging:
  file:
    path: log/gateway/
