spring:
  cloud:
    nacos:
      discovery:
        server-addr: 123.249.77.250:8848
        username: nacos
        password: nacos
      config:
        server-addr: 123.249.77.250:8848
        username: nacos
        password: nacos
        file-extension: properties
        name: ${spring.application.name}