spring:
  application:
    name: kd-notice
  config:
    import: classpath:datasource.yml,classpath:rpc.yml,classpath:cache.yml,classpath:base.yml
server:
  port: 8085
logging:
  file:
    path: log/notice/
